[package]
name = "terminal"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnav Singh <me@arnavion.dev>"]
edition = "2021"

[dependencies]
libc = { version = "0.2.21", default-features = false }
